#You Must Run build script first!
#volumes . -> /home/his
version: '3'
services:
  db:
    container_name: db_mysql
    #image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=his
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d/
    ports:
     - "3306:3306"
#    networks:
#      - his_network
  frontend:
    container_name: frontend_nginx
    restart: always
    build: ./frontend
    volumes:
      - .:/home/his
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
#    networks:
#     - his_network
  middleware:
    container_name: middleware_node
    restart: always
    build: ./middleware
    volumes:
      - .:/home/his
    ports:
     - "8081:8081"
    depends_on:
     - db
     - backend
     - fileserver
    links:
     - fileserver
     - backend
     - db
#    networks:
#      - his_network
  fileserver:
    container_name: fileserver_node
    restart: always
    build: ./fileserver
    volumes:
      - .:/home/his
    ports:
     - "8082:8082"
#    networks:
#      - his_network
  backend:
    container_name: backend_java
    restart: always
    build: ./backend
    volumes:
      - .:/home/his
    depends_on:
     - db
    links:
     - db
    ports:
     - "8080:8080"
#    networks:
#      - his_network

#networks:          
#  his_network:      
#    external: true
